# Numpy
* A library to use for scientific programming, perform calculations on Numpy array (instead doing a loop)

In [1]:
import numpy as np

## Without Numpy

In [2]:
# Here is a serie of triangles
bases = [1.12, 3.21, 8.98, 3.39, 6.72]
heights = [0.89, 4.54, 2.42, 8.27, 5.01]

In [3]:
bases * 0.5 * heights # We cannot manipulate element-wise between 2 array

TypeError: can't multiply sequence by non-int of type 'float'

In [7]:
out = []
for i in range(len(bases)):
    res = 0.5 * bases[i] * heights[i]
    out.append(res)
out


[0.49840000000000007, 7.2867, 10.8658, 14.01765, 16.833599999999997]

## With Numpy

In [8]:
bases = np.array([1.12, 3.21, 8.98, 3.39, 6.72])
heights = np.array([0.89, 4.54, 2.42, 8.27, 5.01])
0.5 * bases * heights 

array([ 0.4984 ,  7.2867 , 10.8658 , 14.01765, 16.8336 ])

In [9]:
type(bases)

numpy.ndarray

## Dtype in Numpy

In [10]:
np.array([1, 2, 3, 'vivadata']) ## notice that it only inclues element with same datatype (convert num to str)

array(['1', '2', '3', 'vivadata'], dtype='<U21')

In [12]:
# You can change the type of `array` values
np.array(['1', '2', '3']).astype(int)

array([1, 2, 3])

In [13]:
np.array([1, 2, 2.5, 3.8]).dtype ## check data type

dtype('float64')

## Manipulating a Numpy

## Create a Numpy

In [16]:
## Create a numpy
print(np.zeros(5, int))
print(np.ones(5, int))
print(np.arange(10))
print(np.linspace(0, 1, 11)) ## from 0 to 1 (inclusive) with 10 points, equal space

[0 0 0 0 0]
[1 1 1 1 1]
[0 1 2 3 4 5 6 7 8 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [18]:
print(np.random.rand(5)) ## random array float

[0.09191025 0.38041995 0.07452217 0.4085785  0.75854285]


In [21]:
np.random.randint(1, 10, 5) # from 1 to 10, take 5 random values

array([6, 1, 3, 7, 3])

## Broadcasting

In [22]:
arr1 = np.random.rand(5)
arr2 = np.random.randint(1, 10, 5)
arr1 * arr2 

array([3.16908267, 0.52044572, 5.00427172, 1.18702273, 3.68946351])

# Indexing, Slicing,Subsetting

In [23]:
arr1[0]

0.6338165332361744

In [26]:
## boolean mask 
print(arr2)
bool_mask = arr2 > 5
print(bool_mask)
print(arr2[bool_mask])

[5 2 8 8 7]
[False False  True  True  True]
[8 8 7]


In [27]:
arr2[arr2>5]

array([8, 8, 7])

## Useful method

* `np.sum`, `np.mean`, `np.median`, `np.std`: sum all elements 
* `np.square`: square all elements 
* `np.sort`: sort all elements
* `np.argsort`: return the indices that sort an array 
* `np.concatenate`: combine 2 arrays 



In [28]:
np.sum(arr2)

30

In [29]:
# sort reverse 
arr2[::-1]

array([7, 8, 8, 2, 5])

# 2-dimensional

* Why we need n-dimensional (Data as matrix, in Algebra)

![numpy-2d-index.png](./images/numpy-2d-index.png)

In [30]:
# Let's create a 2-dimensional `array`:
a = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])

## Check Shape

In [31]:
a 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
print(a.ndim)
print(a.shape)
print(len(a)) 

2
(3, 5)
3


## Subsetting

In [35]:
## subsetting
a[0][1]

1

In [36]:
a[:, 0:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

## Reshaping

In [37]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
a.shape

(3, 5)

In [39]:
a.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [40]:
a.T 

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [41]:
## flatten
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# N-dim array
* All methods are the same

![n-dim-array.png](./images/n-dim-array.png)


In [43]:
y = np.zeros((2, 3, 4), int)
y

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [44]:
y.ndim 

3

In [45]:
## Ref: https://www.kaggle.com/orhansertkaya/numpy-tutorial-for-beginners
## TODO: List of Exercise https://www.w3resource.com/python-exercises/numpy/basic/index.php
### 3, 4, 6, 10, 13, 14, 15, 17, 19

In [ ]:
arr = np.array()